- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: import vpc variables
      include_vars: vars/vpc_setup

    - name: creat v profile vpc
      ec2_vpc_net:
         name: "{{vpc_name}}"
         cidr_block: "{{vpcCidr}}"
         region: "{{region}}"
         dns_support: yes
         dns_hostnames: yes
         tenancy: default
         state: "{{state}}"
      register: vpcout            ## to print and save output variable
    
        #    - debug:
        #        vars: vpcout

    - name: creat public subnet 1 in AZ 1
        ec2_vpc_subnet:
           vpc_id: "{{vpcout.vpc.id}}"
           region: "{{region}}"
           az: "{{zone1}}"
           state: "{{state}}"
           cidr: "{{PubSub1Cidr}}"
           map_public: yes
           resource_tags:
              Name: vprofile-pubsub1
        register: pubsub1_out

    - name: creat public subnet 2 in AZ 2
        ec2_vpc_subnet:
           vpc_id: "{{vpcout.vpc.id}}"
           region: "{{region}}"
           az: "{{zone2}}"
           state: "{{state}}"
           cidr: "{{PubSub2Cidr}}"
           map_public: yes
           resource_tags:
              Name: vprofile-pubsub2
        register: pubsub2_out

    - name: creat public subnet 3 in AZ 3
        ec2_vpc_subnet:
           vpc_id: "{{vpcout.vpc.id}}"
           region: "{{region}}"
           az: "{{zone3}}"
           state: "{{state}}"
           cidr: "{{PubSub3Cidr}}"
           map_public: yes
           resource_tags:
              Name: vprofile-pubsub3
        register: pubsub3_out

    - name: creat private subnet 1 in AZ 1
        ec2_vpc_subnet:
           vpc_id: "{{vpcout.vpc.id}}"
           region: "{{region}}"
           az: "{{zone1}}"
           state: "{{state}}"
           cidr: "{{PrivSub1Cidr}}"
           resource_tags:
              Name: vprofile-privsub1
        register: privsub1_out

    - name: creat private subnet 2 in AZ 2
        ec2_vpc_subnet:
           vpc_id: "{{vpcout.vpc.id}}"
           region: "{{region}}"
           az: "{{zone2}}"
           state: "{{state}}"
           cidr: "{{PrivSub2Cidr}}"
           resource_tags:
              Name: vprofile-privsub2
        register: privsub2_out

    - name: creat private subnet 3 in AZ 3
        ec2_vpc_subnet:
           vpc_id: "{{vpcout.vpc.id}}"
           region: "{{region}}"
           az: "{{zone1}}"
           state: "{{state}}"
           cidr: "{{PrivSub3Cidr}}"
           resource_tags:
              Name: vprofile-privsub3
        register: privsub3_out




